# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dt < Formula
  desc "Dovetail CLI"
  homepage "https://github.com/dovetail/dt"
  version "0.1.0-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dovetail/cli/releases/download/v0.1.0-rc.1/cli_darwin_amd64.tar.gz"
      sha256 "8ffd514fd31f7af12ce0e91dac02275389f04e313c56c54052a34075bc72f89b"

      define_method(:install) do
        bin.install "cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dovetail/cli/releases/download/v0.1.0-rc.1/cli_darwin_arm64.tar.gz"
      sha256 "210039f251bb105e5a07fe2520ff6233ad783cdde895a0abc64077c5e240bc95"

      define_method(:install) do
        bin.install "cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dovetail/cli/releases/download/v0.1.0-rc.1/cli_linux_amd64.tar.gz"
      sha256 "c50a4d9f737fc34366b6d4ecb6ef30d9853d8345c5f35959ea76d37d2436e0d6"
      define_method(:install) do
        bin.install "cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dovetail/cli/releases/download/v0.1.0-rc.1/cli_linux_arm64.tar.gz"
      sha256 "82bb963cac316e1422fcbd9e625d0392ccc9029bb0de6eb24a9a36c7c1f1ff67"
      define_method(:install) do
        bin.install "cli"
      end
    end
  end
end
