# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dt < Formula
  desc "Dovetail CLI"
  homepage "https://github.com/dovetail/dt"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dovetail/cli/releases/download/v0.1.3/dt_darwin_amd64.tar.gz"
      sha256 "c366b5a9712f7a339878b973d8b5e7b04f02c1ed29bbd2a5b13538a9d347d01f"

      define_method(:install) do
        bin.install "dt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dovetail/cli/releases/download/v0.1.3/dt_darwin_arm64.tar.gz"
      sha256 "cd52fbb7b7b3c5e6faacb4cd10e110ef01aa1f3ec6ba22b59506eea9a0f0f25f"

      define_method(:install) do
        bin.install "dt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dovetail/cli/releases/download/v0.1.3/dt_linux_amd64.tar.gz"
      sha256 "e40c36e5c0b2446644a8f0cd47d5145005cfbf9927a36457e4ad1cacf0e07d35"
      define_method(:install) do
        bin.install "dt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dovetail/cli/releases/download/v0.1.3/dt_linux_arm64.tar.gz"
      sha256 "bdd7260748c06ff1a24d64abdf6a7464a0284766359e02e337e82324658ce30c"
      define_method(:install) do
        bin.install "dt"
      end
    end
  end
end
